name: 0 - Run Everything

on:
  workflow_dispatch:
jobs:
  test_django:
    uses: ./.github/workflows/django-test.yml
  build_container:
    needs: test_django
    uses: ./.github/workflows/container.yaml
    secrets:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKERHUB_APP_NAME: ${{ secrets.DOCKERHUB_APP_NAME }}